import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  ISectionChild,
  Packer,
  PageNumber,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";

import { saveAs } from "file-saver";

const COLORS = {
  NAVY: "0D2B55",
  LIGHT: "EAF1FB",
  WHITE: "FFFFFF",
  BORDER: "D9E2F2",
  RED: "C62828",
  GREEN: "1B5E20",
  TEXT: "222222",
  MUTED: "666666",
};

const FONT = "Arial";

/* =========================================================
   TEXT HELPERS
========================================================= */

const headingText = (text: string) =>
  new TextRun({
    text: text,
    bold: true,
    font: FONT,
    size: 34,
    color: COLORS.NAVY,
  });

const paragraph = (
  text: string,
  options?: {
    bold?: boolean;
    color?: string;
    spacingAfter?: number;
    spacingBefore?: number;
  }
) =>
  new Paragraph({
    spacing: {
      before: options?.spacingBefore || 0,
      after: options?.spacingAfter || 70,
    },
    children: [
      new TextRun({
        text: text,
        bold: options?.bold || false,
        color: options?.color || COLORS.TEXT,
        font: FONT,
        size: 20,
      }),
    ],
  });

const bullet = (text: string, color = COLORS.TEXT) =>
  new Paragraph({
    bullet: {
      level: 0,
    },
    spacing: {
      after: 40,
    },
    children: [
      new TextRun({
        text: text,
        color: color,
        font: FONT,
        size: 20,
      }),
    ],
  });

/* =========================================================
   FOOTER
========================================================= */

const footer = new Footer({
  children: [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "Generated by Synlumex AI • Confidential Hiring Document • ",
          font: FONT,
          size: 16,
          color: COLORS.MUTED,
        }),
        new TextRun({
          children: [PageNumber.CURRENT],
          font: FONT,
          size: 16,
          color: COLORS.MUTED,
        }),
      ],
    }),
  ],
});

/* =========================================================
   SECTION HEADER
========================================================= */

const sectionHeader = (text: string) =>
  new Paragraph({
    spacing: {
      before: 250,
      after: 140,
    },
    shading: {
      fill: COLORS.NAVY,
      type: ShadingType.CLEAR,
    },
    indent: {
      left: 120,
      right: 120,
    },
    children: [
      new TextRun({
        text: text,
        bold: true,
        color: COLORS.WHITE,
        size: 24,
        font: FONT,
      }),
    ],
  });

/* =========================================================
   TABLE GENERATOR
========================================================= */

const createTable = (
  headers: string[],
  rows: string[][],
  widths: number[]
) =>
  new Table({
    width: {
      size: 9360,
      type: WidthType.DXA,
    },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: COLORS.BORDER },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: COLORS.BORDER },
      left: { style: BorderStyle.SINGLE, size: 1, color: COLORS.BORDER },
      right: { style: BorderStyle.SINGLE, size: 1, color: COLORS.BORDER },
      insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: COLORS.BORDER },
      insideVertical: { style: BorderStyle.SINGLE, size: 1, color: COLORS.BORDER },
    },
    rows: [
      new TableRow({
        children: headers.map(
          (header, i) =>
            new TableCell({
              width: { size: widths[i], type: WidthType.DXA },
              shading: { fill: COLORS.NAVY, type: ShadingType.CLEAR },
              margins: { top: 120, bottom: 120, left: 120, right: 120 },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: header,
                      bold: true,
                      color: COLORS.WHITE,
                      size: 18,
                      font: FONT,
                    }),
                  ],
                }),
              ],
            })
        ),
      }),
      ...rows.map((row, rowIndex) =>
        new TableRow({
          children: row.map(
            (cell, colIndex) =>
              new TableCell({
                width: { size: widths[colIndex], type: WidthType.DXA },
                shading: {
                  fill: rowIndex % 2 === 0 ? COLORS.WHITE : COLORS.LIGHT,
                  type: ShadingType.CLEAR,
                },
                margins: { top: 120, bottom: 120, left: 120, right: 120 },
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: cell || "",
                        font: FONT,
                        size: 18,
                        color: COLORS.TEXT,
                      }),
                    ],
                  }),
                ],
              })
          ),
        })
      ),
    ],
  });

/* =========================================================
   MARKDOWN / JD EXPORT
========================================================= */

export async function exportMarkdownToDocx(
  markdown: string,
  filename: string
) {
  const lines = markdown.split("\n");
  const children: Paragraph[] = [];

  lines.forEach((rawLine) => {
    const line = rawLine.trim();

    // Blank line — small spacer
    if (!line) {
      children.push(new Paragraph({ spacing: { after: 60 } }));
      return;
    }

    // Legacy # Heading
    if (line.startsWith("# ")) {
      children.push(
        new Paragraph({
          spacing: { before: 200, after: 140 },
          children: [
            new TextRun({
              text: line.replace("# ", ""),
              bold: true,
              color: COLORS.NAVY,
              font: FONT,
              size: 28,
            }),
          ],
        })
      );
      return;
    }

    // Legacy ## Subheading
    if (line.startsWith("## ")) {
      children.push(
        new Paragraph({
          spacing: { before: 160, after: 100 },
          children: [
            new TextRun({
              text: line.replace("## ", ""),
              bold: true,
              color: COLORS.NAVY,
              font: FONT,
              size: 24,
            }),
          ],
        })
      );
      return;
    }

    // Role title line — e.g. "Project Manager (Senior) — Full-time"
    if (line.includes("—") && children.filter((c) => c).length < 3) {
      children.push(
        new Paragraph({
          spacing: { before: 100, after: 200 },
          children: [
            new TextRun({
              text: line,
              bold: true,
              font: FONT,
              size: 32,
              color: COLORS.NAVY,
            }),
          ],
        })
      );
      return;
    }

    // SECTION HEADING — ALL CAPS ending with colon e.g. "KEY RESPONSIBILITIES:"
    if (/^[A-Z][A-Z\s&]+:$/.test(line)) {
      children.push(
        new Paragraph({
          spacing: { before: 260, after: 140 },
          shading: { fill: COLORS.NAVY, type: ShadingType.CLEAR },
          indent: { left: 120, right: 120 },
          children: [
            new TextRun({
              text: line.replace(/:$/, ""),
              bold: true,
              color: COLORS.WHITE,
              size: 22,
              font: FONT,
            }),
          ],
        })
      );
      return;
    }

    // • Key: Value — Hiring Snapshot rows
    if (line.startsWith("•") && line.includes(":")) {
      const content = line.replace(/^•\s*/, "");
      const colonIdx = content.indexOf(":");
      const key = content.substring(0, colonIdx).trim();
      const val = content.substring(colonIdx + 1).trim();
      children.push(
        new Paragraph({
          spacing: { after: 40 },
          children: [
            new TextRun({
              text: key + ": ",
              bold: true,
              font: FONT,
              size: 20,
              color: COLORS.NAVY,
            }),
            new TextRun({
              text: val,
              font: FONT,
              size: 20,
              color: COLORS.TEXT,
            }),
          ],
        })
      );
      return;
    }

    // • Bullet or - bullet
    if (line.startsWith("•") || line.startsWith("- ")) {
      const content = line.replace(/^[•\-]\s*/, "");
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: [
            new TextRun({
              text: content,
              font: FONT,
              size: 20,
              color: COLORS.TEXT,
            }),
          ],
        })
      );
      return;
    }

    // Default — plain paragraph
    children.push(
      new Paragraph({
        spacing: { after: 70 },
        children: [
          new TextRun({
            text: line,
            font: FONT,
            size: 20,
            color: COLORS.TEXT,
          }),
        ],
      })
    );
  });

  const doc = new Document({
    sections: [{ footers: { default: footer }, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, filename.endsWith(".docx") ? filename : filename + ".docx");
}

/* =========================================================
   TALENT REPORT EXPORT
========================================================= */

export async function exportTalentReportToDocx(
  report: any,
  filename: string
) {
  const children: ISectionChild[] = [];

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 350 },
      children: [headingText("TALENT INTELLIGENCE REPORT")],
    })
  );

  children.push(sectionHeader("1. TOP SEARCH KEYWORDS"));

  if (report?.keywords?.boolean_strings?.length) {
    report.keywords.boolean_strings.forEach(
      (keyword: string, index: number) => {
        children.push(paragraph((index + 1).toString() + ". " + keyword));
      }
    );
  }

  if (report?.keywords?.skill_keywords?.length) {
    children.push(
      paragraph("Skill Keywords: " + report.keywords.skill_keywords.join(", "), {
        bold: true,
        color: COLORS.NAVY,
        spacingBefore: 100,
        spacingAfter: 180,
      })
    );
  }

  children.push(sectionHeader("2. BEST SOURCING PLATFORMS"));

  children.push(
    createTable(
      ["Platform", "Why Best for This Role"],
      (report.platforms || []).map((p: any) => [p.name || "", p.reason || ""]),
      [2600, 6760]
    )
  );

  children.push(sectionHeader("3. MARKET SALARY RANGE"));

  children.push(
    createTable(
      ["Level", "India (LPA)", "International (USD)"],
      [
        ["Entry", report?.salary?.india?.entry || "-", report?.salary?.international?.entry || "-"],
        ["Mid", report?.salary?.india?.mid || "-", report?.salary?.international?.mid || "-"],
        ["Senior", report?.salary?.india?.senior || "-", report?.salary?.international?.senior || "-"],
      ],
      [2500, 3430, 3430]
    )
  );

  children.push(
    paragraph(
      "Market Trend: " +
        (report?.salary?.trend || "-") +
        " — " +
        (report?.salary?.trend_reason || "-")
    )
  );

  children.push(sectionHeader("4. TOP COMPANIES TO SOURCE FROM"));

  children.push(
    createTable(
      ["Company", "Type", "Size", "Why Ideal"],
      (report.source_companies || []).map((c: any) => [
        c.name || "",
        c.type || "",
        c.size || "",
        c.reason || "",
      ]),
      [2000, 1800, 1300, 4260]
    )
  );

  children.push(sectionHeader("5. CANDIDATE PERSONA"));

  children.push(paragraph("Ideal Background", { bold: true, color: COLORS.NAVY }));
  children.push(paragraph(report?.candidate_persona?.background || "-"));

  children.push(paragraph("Red Flags", { bold: true, color: COLORS.RED }));

  if (report?.candidate_persona?.red_flags?.length) {
    report.candidate_persona.red_flags.forEach((flag: string) => {
      children.push(bullet(flag, COLORS.RED));
    });
  }

  children.push(
    paragraph("Best Interview Approach", { bold: true, color: COLORS.NAVY })
  );
  children.push(
    paragraph(report?.candidate_persona?.interview_approach || "-")
  );

  children.push(sectionHeader("6. COMPANIES ACTIVELY HIRING"));

  children.push(
    createTable(
      ["Company", "Type", "Size", "Industry", "Why Hiring"],
      (report.hiring_companies || []).map((c: any) => [
        c.name || "",
        c.type || "",
        c.size || "",
        c.industry || "",
        c.reason || "",
      ]),
      [1800, 1400, 1200, 1500, 3460]
    )
  );

  const doc = new Document({
    sections: [{ footers: { default: footer }, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, filename.endsWith(".docx") ? filename : filename + ".docx");
}
