import { useState } from "react";
import PageHeader from "@/components/PageHeader";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Mic, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

export default function InterviewQuestions() {
  const [jd, setJd] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState("technical");

  const generate = async () => {
    try {
      if (jd.trim().length < 30) {
        toast.error("Paste a longer JD");
        return;
      }

      setLoading(true);

      console.log("Sending request to Edge Function...");

      const { data, error } = await supabase.functions.invoke(
       "quick-action",
        {
          body: { jd },
        }
      );

      console.log("Edge Function Response:", data);
      console.log("Edge Function Error:", error);

      if (error) {
        console.error("Invoke Error:", error);

        toast.error(
          error.message || "Failed to generate interview questions"
        );

        return;
      }

      if (!data) {
        toast.error("No data returned");
        return;
      }

      if (data.error) {
        console.error("Function Error:", data.error);

        toast.error(data.error);

        return;
      }

      setResult(data.result);

      toast.success("Interview Questions Generated");

    } catch (err: any) {
      console.error("Frontend Catch Error:", err);

      toast.error(
        err.message || "Something went wrong"
      );
    } finally {
      setLoading(false);
    }
  };

  const diffBadge = (d: string) => {
    const map: any = {
      Easy: "bg-green-100 text-green-800",
      Medium: "bg-yellow-100 text-yellow-800",
      Hard: "bg-red-100 text-red-800",
    };

    return (
      <span
        className={`text-xs font-bold px-2 py-0.5 rounded ${
          map[d] || "bg-gray-100 text-gray-700"
        }`}
      >
        {d}
      </span>
    );
  };

  const tabs = [
    { key: "technical", label: "🧠 Technical" },
    { key: "behavioral", label: "🎯 Behavioral" },
    { key: "situational", label: "🔥 Situational" },
    { key: "culture_fit", label: "🤝 Culture Fit" },
    { key: "role_specific", label: "💼 Role Specific" },
    { key: "structure", label: "📋 Structure" },
    { key: "scorecard", label: "✅ Scorecard" },
  ];

  return (
    <>
      <PageHeader
        title="Interview Questions"
        description="Generate role-specific interview questions instantly from any JD."
      />

      <Card className="p-5 shadow-soft-sm mb-6">
        <Textarea
          value={jd}
          onChange={(e) => setJd(e.target.value)}
          placeholder="Paste a job description here..."
          rows={6}
          className="text-sm"
        />

        <div className="flex items-center justify-between mt-3">
          <p className="text-xs text-muted-foreground">
            {jd.length} characters
          </p>

          <Button
            onClick={generate}
            disabled={loading}
            className="bg-gradient-brand text-brand-foreground hover:opacity-95 shadow-glow"
          >
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Mic className="h-4 w-4 mr-2" />
                Generate Questions
              </>
            )}
          </Button>
        </div>
      </Card>

      {!result && !loading && (
        <Card className="p-12 text-center border-2 border-dashed shadow-none bg-transparent">
          <Mic className="h-10 w-10 mx-auto text-muted-foreground/50 mb-3" />

          <p className="text-sm text-muted-foreground">
            Paste a JD and click Generate Questions.
          </p>
        </Card>
      )}

      {result && (
        <div className="rounded-lg overflow-hidden border border-gray-200 shadow-md">

          <div
            style={{ background: "#0f2744" }}
            className="px-6 py-4"
          >
            <h2 className="text-white font-bold text-lg tracking-tight">
              📋 Interview Question Bank
            </h2>

            <p className="text-blue-300 text-xs mt-1">
              Generated by JARVIS
            </p>
          </div>

          <div className="flex overflow-x-auto border-b-2 border-[#1a3a5c] bg-gray-50">
            {tabs.map((t) => (
              <button
                key={t.key}
                onClick={() => setActiveTab(t.key)}
                className={`px-4 py-2.5 text-xs font-semibold whitespace-nowrap border-b-2 transition-all ${
                  activeTab === t.key
                    ? "border-[#1a3a5c] text-[#1a3a5c] bg-white"
                    : "border-transparent text-gray-500 hover:bg-gray-100"
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>

          <div className="bg-white p-6">

            {activeTab === "technical" && (
              <div className="space-y-4">
                {result.technical?.map((q: any, i: number) => (
                  <Card key={i} className="p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h3 className="font-semibold text-sm">
                        {i + 1}. {q.question}
                      </h3>

                      {diffBadge(q.difficulty)}
                    </div>

                    <p className="text-xs text-gray-500 mb-2">
                      {q.category}
                    </p>

                    <ul className="list-disc pl-5 text-xs text-gray-700 space-y-1">
                      {q.ideal_answer_points?.map((p: string, j: number) => (
                        <li key={j}>{p}</li>
                      ))}
                    </ul>
                  </Card>
                ))}
              </div>
            )}

            {activeTab === "behavioral" && (
              <div className="space-y-4">
                {result.behavioral?.map((q: any, i: number) => (
                  <Card key={i} className="p-4">
                    <h3 className="font-semibold text-sm mb-2">
                      {i + 1}. {q.question}
                    </h3>

                    <p className="text-xs text-blue-700 mb-2">
                      {q.competency}
                    </p>

                    <ul className="list-disc pl-5 text-xs text-gray-700">
                      {q.star_prompts?.map((p: string, j: number) => (
                        <li key={j}>{p}</li>
                      ))}
                    </ul>
                  </Card>
                ))}
              </div>
            )}

            {activeTab === "situational" && (
              <pre className="text-xs overflow-auto whitespace-pre-wrap">
                {JSON.stringify(result.situational, null, 2)}
              </pre>
            )}

            {activeTab === "culture_fit" && (
              <pre className="text-xs overflow-auto whitespace-pre-wrap">
                {JSON.stringify(result.culture_fit, null, 2)}
              </pre>
            )}

            {activeTab === "role_specific" && (
              <pre className="text-xs overflow-auto whitespace-pre-wrap">
                {JSON.stringify(result.role_specific, null, 2)}
              </pre>
            )}

            {activeTab === "structure" && (
              <pre className="text-xs overflow-auto whitespace-pre-wrap">
                {JSON.stringify(result.interview_structure, null, 2)}
              </pre>
            )}

            {activeTab === "scorecard" && (
              <pre className="text-xs overflow-auto whitespace-pre-wrap">
                {JSON.stringify(result.scorecard, null, 2)}
              </pre>
            )}

          </div>
        </div>
      )}
    </>
  );
}
